/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brian_gl.mvsicplayer.frames;

import brian_gl.mvsicplayer.lang.Language;
import brian_gl.mvsicplayer.lang.LanguageText;

/**
 *
 * @author LENOVO
 */
public class MusicPlayerFrame extends javax.swing.JFrame {

    /**Language Class To Set Language Local Text In Frame*/
    private LanguageText _LanguageText;
    
    /**
     * Creates new form MusicPlayerFrame
     */
    public MusicPlayerFrame() {
        _LanguageText = new LanguageText(Language.SPANISH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        menuBar = new javax.swing.JMenuBar();
        menuItemFiles = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mvsic Player");
        setMinimumSize(new java.awt.Dimension(900, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("musicPlayerFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 700));

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setMaximumSize(new java.awt.Dimension(32767, 32));
        menuBar.setMinimumSize(new java.awt.Dimension(900, 32));
        menuBar.setName(""); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(900, 32));

        menuItemFiles.setText(_LanguageText.MenuItemFiles());
        menuItemFiles.setToolTipText(_LanguageText.MenuItemFilesTooltip());
        menuBar.add(menuItemFiles);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuItemFiles;
    // End of variables declaration//GEN-END:variables

    
    
}
