/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brian_gl.mvsicplayer.frames;

import brian_gl.mvsicplayer.lang.Language;
import brian_gl.mvsicplayer.lang.LanguageText;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class MusicPlayerFrame extends javax.swing.JFrame {

    /**Language Class To Set Language Local Text In Frame*/
    private LanguageText _LanguageText;
    
    /**
     * Creates new form MusicPlayerFrame
     */
    public MusicPlayerFrame() {
        
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        playerPanel = new javax.swing.JPanel();
        coverArtPreviousNextPanel = new javax.swing.JPanel();
        previousTrackLabel = new javax.swing.JLabel();
        coverArtLabel = new javax.swing.JLabel();
        nextTrackLabel = new javax.swing.JLabel();
        titleAlbumLabel = new javax.swing.JLabel();
        artistLabel = new javax.swing.JLabel();
        durationProgressLabel = new javax.swing.JLabel();
        progressSlider = new javax.swing.JSlider();
        menuBar = new javax.swing.JMenuBar();
        fileMenuItem = new javax.swing.JMenu();
        preferencesMenuItem = new javax.swing.JMenu();
        languageMenu = new javax.swing.JMenu();
        spanishRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        englishRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();

        languageButtonGroup.add(spanishRadioButtonMenuItem);
        languageButtonGroup.add(englishRadioButtonMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mvsic Player");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("musicPlayerFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setMinimumSize(new java.awt.Dimension(900, 668));
        mainPanel.setLayout(new java.awt.CardLayout());

        playerPanel.setMinimumSize(new java.awt.Dimension(900, 668));
        playerPanel.setOpaque(false);

        coverArtPreviousNextPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        coverArtPreviousNextPanel.setPreferredSize(new java.awt.Dimension(900, 500));

        previousTrackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previousTrackLabel.setText("<html><p style='font-size:50px;'>&#x227A;</p></html>");
        previousTrackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousTrackLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousTrackLabel.setMinimumSize(new java.awt.Dimension(150, 475));
        previousTrackLabel.setPreferredSize(new java.awt.Dimension(150, 475));
        previousTrackLabel.setRequestFocusEnabled(false);
        previousTrackLabel.setVerifyInputWhenFocusTarget(false);

        coverArtLabel.setBackground(new java.awt.Color(255, 255, 255));
        coverArtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coverArtLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coverArtLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        coverArtLabel.setMinimumSize(new java.awt.Dimension(475, 475));
        coverArtLabel.setPreferredSize(new java.awt.Dimension(475, 475));

        nextTrackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextTrackLabel.setText("<html><p style='font-size:50px;'>&#x227B;</p></html>");
        nextTrackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextTrackLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextTrackLabel.setMinimumSize(new java.awt.Dimension(150, 475));
        nextTrackLabel.setPreferredSize(new java.awt.Dimension(150, 475));
        nextTrackLabel.setRequestFocusEnabled(false);
        nextTrackLabel.setVerifyInputWhenFocusTarget(false);

        titleAlbumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAlbumLabel.setText("<html><b>Title</b> - <i>Album</i></html>");
        titleAlbumLabel.setToolTipText("");
        titleAlbumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleAlbumLabel.setMaximumSize(new java.awt.Dimension(32780, 40));
        titleAlbumLabel.setMinimumSize(new java.awt.Dimension(37, 24));
        titleAlbumLabel.setPreferredSize(new java.awt.Dimension(37, 24));

        artistLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        artistLabel.setText("Artist");
        artistLabel.setToolTipText("");
        artistLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artistLabel.setMaximumSize(new java.awt.Dimension(32780, 40));
        artistLabel.setMinimumSize(new java.awt.Dimension(37, 24));
        artistLabel.setPreferredSize(new java.awt.Dimension(37, 24));

        durationProgressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationProgressLabel.setText("<html><i>00:00 / 00:00</i></html>");
        durationProgressLabel.setToolTipText("");
        durationProgressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        durationProgressLabel.setMaximumSize(new java.awt.Dimension(32780, 40));
        durationProgressLabel.setMinimumSize(new java.awt.Dimension(37, 24));
        durationProgressLabel.setPreferredSize(new java.awt.Dimension(37, 24));

        progressSlider.setToolTipText("");

        javax.swing.GroupLayout coverArtPreviousNextPanelLayout = new javax.swing.GroupLayout(coverArtPreviousNextPanel);
        coverArtPreviousNextPanel.setLayout(coverArtPreviousNextPanelLayout);
        coverArtPreviousNextPanelLayout.setHorizontalGroup(
            coverArtPreviousNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverArtPreviousNextPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousTrackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(coverArtPreviousNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(durationProgressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleAlbumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coverArtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(nextTrackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coverArtPreviousNextPanelLayout.setVerticalGroup(
            coverArtPreviousNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverArtPreviousNextPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(coverArtPreviousNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(coverArtLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previousTrackLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextTrackLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleAlbumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(durationProgressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coverArtPreviousNextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(coverArtPreviousNextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
        );

        mainPanel.add(playerPanel, "player");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        menuBar.setBorder(null);
        menuBar.setMaximumSize(new java.awt.Dimension(32767, 32));
        menuBar.setMinimumSize(new java.awt.Dimension(900, 32));
        menuBar.setName(""); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(900, 32));

        fileMenuItem.setText("<html><b>File</b></html>");
        fileMenuItem.setToolTipText("");
        fileMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(fileMenuItem);

        preferencesMenuItem.setText("<html><b>Preferences</b></html>");
        preferencesMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        languageMenu.setText("<html>Languague</html>");
        languageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        spanishRadioButtonMenuItem.setSelected(true);
        spanishRadioButtonMenuItem.setText("<html><b><i>Español</i></b></html>");
        spanishRadioButtonMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spanishRadioButtonMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spanishRadioButtonMenuItemMousePressed(evt);
            }
        });
        languageMenu.add(spanishRadioButtonMenuItem);

        englishRadioButtonMenuItem.setText("<html><b><i>English</i></b></html>");
        englishRadioButtonMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        englishRadioButtonMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                englishRadioButtonMenuItemMousePressed(evt);
            }
        });
        languageMenu.add(englishRadioButtonMenuItem);

        preferencesMenuItem.add(languageMenu);

        menuBar.add(preferencesMenuItem);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        evt.getWindow().dispose(); System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void englishRadioButtonMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_englishRadioButtonMenuItemMousePressed
        // TODO add your handling code here:
        setLanguage(Language.ENGLISH);
    }//GEN-LAST:event_englishRadioButtonMenuItemMousePressed

    private void spanishRadioButtonMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spanishRadioButtonMenuItemMousePressed
        // TODO add your handling code here:
        setLanguage(Language.SPANISH);
    }//GEN-LAST:event_spanishRadioButtonMenuItemMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artistLabel;
    private javax.swing.JLabel coverArtLabel;
    private javax.swing.JPanel coverArtPreviousNextPanel;
    private javax.swing.JLabel durationProgressLabel;
    private javax.swing.JRadioButtonMenuItem englishRadioButtonMenuItem;
    private javax.swing.JMenu fileMenuItem;
    private javax.swing.ButtonGroup languageButtonGroup;
    private javax.swing.JMenu languageMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nextTrackLabel;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JMenu preferencesMenuItem;
    private javax.swing.JLabel previousTrackLabel;
    private javax.swing.JSlider progressSlider;
    private javax.swing.JRadioButtonMenuItem spanishRadioButtonMenuItem;
    private javax.swing.JLabel titleAlbumLabel;
    // End of variables declaration//GEN-END:variables

    private void customInitComponents(){
        
       try {
                
            //Set frame icon:
            File resourcesDirectory = new File("src/main/resources/img/mvsic-player-logo-simple.png");
            Image iconImage = Toolkit.getDefaultToolkit().getImage(resourcesDirectory.toURI().toURL());
            setIconImage(iconImage);
            iconImage.flush();

            //Set language:
            _LanguageText = new LanguageText();
            setLanguage(Language.SPANISH);

        } catch (MalformedURLException ex) {

        } 
    }
    
    private void setLanguage(Language language){
        
         _LanguageText.setLanguage(language);
        
        //Menu Items:
        fileMenuItem.setText(_LanguageText.MenuItemFileText());
        fileMenuItem.setToolTipText(_LanguageText.MenuItemFileTooltipText());
        
        preferencesMenuItem.setText(_LanguageText.MenuItemPreferencesText());
        preferencesMenuItem.setToolTipText(_LanguageText.MenuItemPreferencesTooltipText());
        
        //Menus:
        languageMenu.setText(_LanguageText.MenuLanguageText());
        languageMenu.setToolTipText(_LanguageText.MenuLanguageTooltipText());
        
        //Labels:
        
        titleAlbumLabel.setText(_LanguageText.LabelTitleAlbumText());
        titleAlbumLabel.setToolTipText(_LanguageText.LabelTitleAlbumTooltipText());
        
        artistLabel.setText(_LanguageText.LabelArtistText());
        artistLabel.setToolTipText(_LanguageText.LabelArtistTooltipText());
        
        durationProgressLabel.setToolTipText(_LanguageText.LabelDurationProgressTooltipText());
        
        previousTrackLabel.setToolTipText(_LanguageText.LabelPreviousTrackTooltipText());
        
        nextTrackLabel.setToolTipText(_LanguageText.LabelNextTrackTooltipText());
    }
    
}
